config/routes.rb
Programmerstoknow::Application.routes.draw do
  resources :programmers

  root :to => 'programmers#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/models/programmer.rb
class Programmer < ActiveRecord::Base
  attr_accessible :name, :tag_line, :sidebox_info, :image_url, :wiki_url


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/programmers_controller.rb
class ProgrammersController < ApplicationController
  # GET /programmers
  # GET /programmers.json
  def index
    @programmers = Programmer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @programmers }
    end
  end

  # GET /programmers/1
  # GET /programmers/1.json
  def show
    @programmer = Programmer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @programmer }
    end
  end

  # GET /programmers/new
  # GET /programmers/new.json
  def new
    @programmer = Programmer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @programmer }
    end
  end

  # GET /programmers/1/edit
  def edit
    @programmer = Programmer.find(params[:id])
  end

  # POST /programmers
  # POST /programmers.json
  def create
    @programmer = Programmer.new(params[:programmer])

    respond_to do |format|
      if @programmer.save
        format.html { redirect_to @programmer, notice: 'Programmer was successfully created.' }
        format.json { render json: @programmer, status: :created, location: @programmer }
      else
        format.html { render action: "new" }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /programmers/1
  # PUT /programmers/1.json
  def update
    @programmer = Programmer.find(params[:id])

    respond_to do |format|
      if @programmer.update_attributes(params[:programmer])
        format.html { redirect_to @programmer, notice: 'Programmer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @programmer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programmers/1
  # DELETE /programmers/1.json
  def destroy
    @programmer = Programmer.find(params[:id])
    @programmer.destroy

    respond_to do |format|
      format.html { redirect_to programmers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programmers_helper.rb
module ProgrammersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Programmerstoknow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/programmers/_form.html.erb
<%= form_for(@programmer) do |f| %>
  <% if @programmer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programmer.errors.count, "error") %> prohibited this programmer from being saved:</h2>

      <ul>
      <% @programmer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programmers/edit.html.erb
<h1>Editing programmer</h1>

<%= render 'form' %>

<%= link_to 'Show', @programmer %> |
<%= link_to 'Back', programmers_path %>

app/views/programmers/index.html.erb
<script src="/path/to/jquery.masonry.min.js"></script>

<!-- <h1>Flatiron School Presents <br> <br>
Programmers to know<br> <br>
True bosses in the game </h1> -->


<body class="homepage ">
  
<div id="loading-image">
  <p align="center"><img src="assets/loading.jpg" alt="Loading..." height="169px" width="460px" align="center"/></p>
</div>

<section id="content">
    
    <div id="container" class="transitions-enabled clearfix">
  
    <div class="item big-text col2">
      <br/>
      <img src="assets/flatiron.png" align="left">Flatiron School Presents<br />
      Programmers to know<br />
      True bosses in the game
      <br/>
    </div>

  <% @programmers.each do |programmer| %>
    <div class="item">
              <a href="<%= programmer.wiki_url %>">
                <% if !programmer.image_url.nil? %>
                <img width="200px;" src="<%= programmer.image_url %>">
                <% end %>
              <h2><%= programmer.name %></h2></a>
              <p><%= programmer.tag_line %></p>
    <div class="clear"></div>
    </div>
  <% end %>

</div> <!-- #container -->

<script src="js/jquery-1.7.1.min.js"></script>
<script src="jquery.masonry.min.js"></script>
<script src="js/utils.js"></script>
<script src="js/flip-card.js"></script>
<script type="text/javascript">

var $container = $('#container');
$container.imagesLoaded(function(){
  $container.masonry({
    itemSelector : '.item',
    columnWidth : 240,
    isAnimated: true,
    animationOptions: {
    duration: 150,
    easing: 'linear',
    queue: true
    }  
  });
});


$(window).load(function(){
  $('#loading-image').slideUp('slow');
  $('#container').masonry({
  });
});
</script>

    <footer id="site-footer">
      By <a href="http://students.flatironschool.com/davidbaker.html">David Baker</a> &amp; <a href="http://students.flatironschool.com/akivaleeder.html">Akiva Leeder</a> at <a href="http://flatironschool.com">The Flatiron School</a>
    </footer>
    
  </section> <!-- #content -->

</body>

<!-- 



<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @programmers.each do |programmer| %>
  <tr>
    <td><%= programmer.name %></td>
    <td><%= link_to 'Show', programmer %></td>
    <td><%= link_to 'Edit', edit_programmer_path(programmer) %></td>
    <td><%= link_to 'Destroy', programmer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Programmer', new_programmer_path %> -->

app/views/programmers/new.html.erb
<h1>New programmer</h1>

<%= render 'form' %>

<%= link_to 'Back', programmers_path %>

app/views/programmers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_programmer_path(@programmer) %> |
<%= link_to 'Back', programmers_path %>